=== didier-tp/xml_9Novembre2020/tp_xml_v2005/xml_+_schema/id_ref_personne_adresse/schema_id_ref.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE xsd:schema SYSTEM "./XMLSchema.dtd"> -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


    <xsd:annotation>
		<xsd:documentation>Annuaire avec id et idref</xsd:documentation>
	</xsd:annotation>


	
		
<xsd:element name="annuaire" type="annuaireType">

    <!-- attribut id définit en tant que clef primaire sur pays -->
	<xsd:key name="PaysKey">
    	<xsd:selector xpath="pays" />
    	<xsd:field xpath="@id" />
	</xsd:key>


	<!-- attribut id définit en tant que clef primaire sur adresse -->
	<xsd:key name="AdresseKey">
    	<xsd:selector xpath="adresse" />
    	<xsd:field xpath="@id" />
	</xsd:key>

	
	<!-- contrainte d'intégrité : personne/@idAdr vers adresse/@id --> 
	<xsd:keyref name="PersonneToAdresse" refer="AdresseKey">
    	<xsd:selector xpath="personne" />
    	<xsd:field xpath="@idAdr" />
	</xsd:keyref>

</xsd:element>
	
<xsd:complexType name="annuaireType">
	
    
	
	
	<xsd:sequence>
	    <xsd:element name="pays" type="paysType" minOccurs="0" maxOccurs="unbounded" />					
	    <xsd:element name="adresse" type="adresseType" minOccurs="0" maxOccurs="unbounded" />					
		<xsd:element name="personne" type="personneType" minOccurs="0" maxOccurs="unbounded" />					
	</xsd:sequence>
		
	
</xsd:complexType>


<xsd:complexType name="paysType">
	<xsd:sequence>
		<xsd:element name="nom" type="xsd:string"/>
		<xsd:element name="capitale" type="xsd:string" />		
	</xsd:sequence>
	<!-- <xsd:attribute name="id" type="xsd:ID" /> -->
	<xsd:attribute name="id" type="xsd:string"  /> <!-- voir <xsd:key>  -->
</xsd:complexType>	

	
<xsd:complexType name="adresseType">
	<xsd:sequence>
		<xsd:element name="rue" type="xsd:string"/>
		<xsd:element name="cp" type="xsd:integer" />
		<xsd:element name="ville" type="xsd:string" />
	</xsd:sequence>
	<!-- <xsd:attribute name="id" type="xsd:ID" /> -->
	<xsd:attribute name="id" type="xsd:string"  /> <!-- voir <xsd:key> -->
</xsd:complexType>	
					
<xsd:complexType name="personneType">
	<xsd:sequence>
		<xsd:element name="nom" type="xsd:string"/>
		<xsd:element name="prenom" type="xsd:string" />		
	</xsd:sequence>
	<!-- <xsd:attribute name="idAdr" type="xsd:IDREF" /> -->
     <xsd:attribute name="idAdr" type="xsd:string" /> <!-- voir <xsd:keyref> -->
</xsd:complexType>	

			
	
</xsd:schema>

=== didier-tp/xml_9Novembre2020/tp_xml_v2005/xml_+_schema/id_ref_personne_adresse/essai_id_ref.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<annuaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="schema_id_ref.xsd">
               
    <pays id="1">
       <nom>France</nom>
       <capitale>Paris</capitale>
    </pays>   
    
    <pays id="2">
       <nom>Allemagne</nom>
       <capitale>Berlin</capitale>
    </pays>         
               
	<adresse id="1">
		<rue>1, rue elle</rue>
		<cp>75001</cp>
		<ville>Paris</ville>
	</adresse>
	
	<adresse id="2">
		<rue>1, rue 2</rue>
		<cp>80000</cp>
		<ville>Amiens</ville>
	</adresse>
	
	<personne idAdr="1">
		<nom>dupond</nom>
		<prenom>luc</prenom>		
	</personne>
	
	<personne idAdr="1">
		<nom>dupond</nom>
		<prenom>julie</prenom>		
	</personne>


	<personne idAdr="2">
		<nom>durant</nom>		
		<prenom>paul</prenom>
	</personne>

	
</annuaire>
