=== didier-tp/xml_9Novembre2020/tp_xml_v2005/xml_+_schema/ex_id_ref_livre_auteur/schema_ex_id_ref.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:annotation>
		<xsd:documentation>biblio avec liaison  </xsd:documentation>
	</xsd:annotation>

		
<xsd:element name="biblio" type="biblioType">

    <!-- attribut id définit en tant que clef primaire sur personne -->
	<xsd:key name="PersonneKey">
    	<xsd:selector xpath="personne" />
    	<xsd:field xpath="@id" />
	</xsd:key>

	
	<!-- contrainte d'intégrité : livre/@auteur vers personne/@id --> 
	<xsd:keyref name="LivreToPersonne" refer="PersonneKey">
    	<xsd:selector xpath="livre" />
    	<xsd:field xpath="@auteur" />
	</xsd:keyref>

</xsd:element>
	
<xsd:complexType name="biblioType">
	<xsd:sequence>	    
	    <xsd:element name="livre" type="livreType" minOccurs="0" maxOccurs="unbounded" />
	    <xsd:element name="personne" type="personneType" minOccurs="0" maxOccurs="unbounded" />
	</xsd:sequence>
</xsd:complexType>
	
<xsd:complexType name="livreType">
	<xsd:sequence>
		<xsd:element name="titre" type="xsd:string"/>
		<xsd:element name="editeur" type="xsd:string" />
	</xsd:sequence>
	<xsd:attribute name="auteur" type="xsd:string"  /> 
</xsd:complexType>	
					
<xsd:complexType name="personneType">
	<xsd:sequence>
		<xsd:element name="nom" type="xsd:string"/>
		<xsd:element name="prenom" type="xsd:string" />		
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:string" />
</xsd:complexType>	
		
</xsd:schema>

=== didier-tp/xml_9Novembre2020/tp_xml_v2005/xml_+_schema/ex_id_ref_livre_auteur/exemple_id_ref.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<biblio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="schema_ex_id_ref.xsd">
               
	<livre auteur="1">
		<titre>Livre A</titre>
		<editeur>Eyrolles</editeur>		
	</livre>
	
    <livre auteur="1">
		<titre>Livre B</titre>
		<editeur>Masson</editeur>		
	</livre>

    <livre auteur="2">
		<titre>Livre C</titre>
		<editeur>InterEditions</editeur>		
	</livre>

	
	<personne id="1">
		<nom>durant</nom>
		<prenom>luc</prenom>		
	</personne>
	
	<personne id="2">
		<nom>dupond</nom>
		<prenom>julie</prenom>		
	</personne>
	
</biblio>
